basePath: /api
definitions:
  application.AuthResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
  application.DashboardSummary:
    properties:
      category_totals:
        additionalProperties:
          format: float64
          type: number
        type: object
      monthly_trends:
        additionalProperties:
          format: float64
          type: number
        type: object
      net_balance:
        type: number
      recent_activity:
        items:
          $ref: '#/definitions/domain.Record'
        type: array
      total_expenses:
        type: number
      total_income:
        type: number
      weekly_trends:
        additionalProperties:
          format: float64
          type: number
        type: object
    type: object
  domain.Record:
    properties:
      amount:
        type: number
      category:
        type: string
      created_at:
        type: string
      created_by:
        type: integer
      date:
        type: string
      id:
        type: integer
      note:
        type: string
      type:
        $ref: '#/definitions/domain.RecordType'
      updated_at:
        type: string
    type: object
  domain.RecordType:
    enum:
    - INCOME
    - EXPENSE
    type: string
    x-enum-varnames:
    - TypeIncome
    - TypeExpense
  domain.Role:
    enum:
    - VIEWER
    - ANALYST
    - ADMIN
    type: string
    x-enum-varnames:
    - RoleViewer
    - RoleAnalyst
    - RoleAdmin
  domain.User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      role:
        $ref: '#/definitions/domain.Role'
      updated_at:
        type: string
      username:
        type: string
    type: object
  errors.AppError:
    properties:
      details:
        items:
          type: string
        type: array
      error:
        type: string
    type: object
  http.loginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  http.refreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Production-grade Finance Backend with DDD and RBAC.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: LedgeGuard API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return tokens
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/application.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Login user
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Use refresh token to get a new access token
      parameters:
      - description: Refresh request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.refreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/application.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Refresh access token
      tags:
      - auth
  /dashboard/summary:
    get:
      description: Get total income, expenses, and category-wise totals
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/application.DashboardSummary'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      security:
      - BearerAuth: []
      summary: Get dashboard summary
      tags:
      - dashboard
  /records:
    get:
      description: Get records with advanced filtering and pagination.
      parameters:
      - description: Filter start (YYYY-MM-DD)
        in: query
        name: start_date
        type: string
      - description: Filter end (YYYY-MM-DD)
        in: query
        name: end_date
        type: string
      - description: Filter by type (INCOME/EXPENSE)
        in: query
        name: type
        type: string
      - description: Filter by category
        in: query
        name: category
        type: string
      - description: Page number (default 1)
        in: query
        name: page
        type: integer
      - description: Page size (default 10)
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Record'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      security:
      - BearerAuth: []
      summary: List financial records
      tags:
      - records
    post:
      consumes:
      - application/json
      description: Add a new income or expense entry. Admin only.
      parameters:
      - description: Record object
        in: body
        name: record
        required: true
        schema:
          $ref: '#/definitions/domain.Record'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Record'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      security:
      - BearerAuth: []
      summary: Create a financial record
      tags:
      - records
  /records/{id}:
    delete:
      description: Soft delete a record. Admin only.
      parameters:
      - description: Record ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      security:
      - BearerAuth: []
      summary: Delete a financial record
      tags:
      - records
    put:
      consumes:
      - application/json
      description: Modify an existing record. Admin only.
      parameters:
      - description: Record ID
        in: path
        name: id
        required: true
        type: integer
      - description: Record object
        in: body
        name: record
        required: true
        schema:
          $ref: '#/definitions/domain.Record'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Record'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      security:
      - BearerAuth: []
      summary: Update a financial record
      tags:
      - records
  /users:
    get:
      description: Get a list of all users. Admin only.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      security:
      - BearerAuth: []
      summary: List all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new system user. Admin only.
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      security:
      - BearerAuth: []
      summary: Create a new user
      tags:
      - users
  /users/{id}:
    delete:
      description: Deactivate a user. Admin only.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      security:
      - BearerAuth: []
      summary: Delete a user (Soft Delete)
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update an existing user. Admin only.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      security:
      - BearerAuth: []
      summary: Update a user
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
